# Generated by Django 5.2.6 on 2026-07-16 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messmetapp', '0010_popupnotice'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Owner name', max_length=150)),
                ('title', models.CharField(default='Owner', help_text='Title/Position', max_length=100)),
                ('image', models.ImageField(upload_to='owner/')),
                ('description', models.TextField(blank=True, help_text='Brief description about the owner')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Owner Image',
                'verbose_name_plural': 'Owner Images',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StaffImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Staff member name', max_length=150)),
                ('role', models.CharField(blank=True, help_text='Staff role/position', max_length=100)),
                ('image', models.ImageField(upload_to='staff/')),
                ('description', models.TextField(blank=True, help_text='Brief description about the staff member')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (higher numbers first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Staff Image',
                'verbose_name_plural': 'Staff Images',
                'ordering': ['-order', '-created_at'],
            },
        ),
    ]
